[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     debug #info
    Parsers_File  parsers.conf

[FILTER]
    Name          modify
    Match         *  # или укажите конкретный Tag
    # Обрезаем time до 23 символов: YYYY-MM-DDTHH:MM:SS.LLL + Z
    Set           time_ms $time:0:23$Z
    # Удаляем исходное поле time (чтобы не дублировалось)
    Remove        time


[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker-ms  # используем новый парсер
    Tag               staff-app-logs
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On


[OUTPUT]
    Name            opensearch
    Host            opensearch-staff-node1
    Port            9200
    Index           staff-logs-%Y.%m.%d
    Suppress_Type_Name On
    HTTP_User       login_admin
    HTTP_Passwd     password
    Logstash_Prefix fluent-bit
    logstash_format false
    Replace_Dots    true
    Retry_Limit     3

