[PARSER]
    Name        docker-raw
    Format      json
    Time_Key    time
    # Просто сохраняем время как строку (не разбираем)
    Reserve_Data True

[PARSER]
    Name        docker-ms
    Format      regex
    Regex       ^(?<time_ms>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)$
    Time_Key     time_ms
    Time_Format  %Y-%m-%dT%H:%M:%S.%L000Z  # 3 цифры + 3 нуля = 6 цифр для %f
    Time_Keep   On

