spring.datasource.url=${GTRK_POSTGRESS_DB_HOST}:${GTRK_POSTGRESS_DB_PORT}/appdb
spring.datasource.username=${GTRK_POSTGRESS_DB_USERNAME}
spring.datasource.password=${GTRK_POSTGRESS_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-bean-definition-overriding=true
spring.http.multipart.enabled=true
file.uploadDir=${LOAD_1C}
server.http2.enabled=true
server.port=${SERVER_PORT}
server.ssl.certificate=${SSL_SERTIFICATE}
server.ssl.certificate-private-key=${SSL_PRIVATE_KEY}
server.ssl.trust-store=${TRUSTSTORE}
server.ssl.trust-store-password=${password} #пароль для подписи java поставить свой
server.ssl.trust-store-type=JKS
server.uri=${HOST_URI}
spring.messages.basename=validation
loadXMLDelay=10000
app.dirLoadXML=${LOAD_SKUD}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${ISSUER_URI}/realms/gtrk/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI}/realms/gtrk
authserver.uri=${ISSUER_URI}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB
spring.servlet.multipart.resolve-lazily=true

logging.pattern.console='%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n'
logging.pattern.config="classpath:logback-spring.xml"

